# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "image_resizer"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Nelson"]
  s.date = "2012-04-30"
  s.description = "Image resizing gem (requires ImageMagick)"
  s.email = "daniel@populr.me"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "image_resizer.gemspec",
    "lib/image_resizer.rb",
    "lib/image_resizer/analyzer.rb",
    "lib/image_resizer/configurable.rb",
    "lib/image_resizer/encoder.rb",
    "lib/image_resizer/has_filename.rb",
    "lib/image_resizer/loggable.rb",
    "lib/image_resizer/processor.rb",
    "lib/image_resizer/shell.rb",
    "lib/image_resizer/temp_object.rb",
    "lib/image_resizer/utils.rb",
    "samples/DSC02119.JPG",
    "samples/a.jp2",
    "samples/beach.jpg",
    "samples/beach.png",
    "samples/egg.png",
    "samples/landscape.png",
    "samples/round.gif",
    "samples/sample.docx",
    "samples/taj.jpg",
    "samples/white pixel.png",
    "spec/image_resizer/analyzer_spec.rb",
    "spec/image_resizer/configurable_spec.rb",
    "spec/image_resizer/encoder_spec.rb",
    "spec/image_resizer/has_filename_spec.rb",
    "spec/image_resizer/loggable_spec.rb",
    "spec/image_resizer/processor_spec.rb",
    "spec/image_resizer/shell_spec.rb",
    "spec/image_resizer/temp_object_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/argument_matchers.rb",
    "spec/support/image_matchers.rb",
    "spec/support/simple_matchers.rb",
    "tmp/test_file"
  ]
  s.homepage = "http://github.com/populr/image_resizer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Image resizing gem (requires ImageMagick)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<pry-nav>, [">= 0"])
      s.add_development_dependency(%q<pry-stack_explorer>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<pry-nav>, [">= 0"])
      s.add_dependency(%q<pry-stack_explorer>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<pry-nav>, [">= 0"])
    s.add_dependency(%q<pry-stack_explorer>, [">= 0"])
  end
end

